import { NextRequest, NextResponse } from 'next/server';
import { sanityWriteClient } from '@/lib/sanity';
import { assignSlugs } from '@/lib/itemSlug';
import iconManifest from '@/lib/itemIconManifest.json';
import nameManifest from '@/lib/itemLocalizationMap.json';

// Locally-mirrored item icons. Generated by scripts/mirror-item-icons.js so
// the cron preserves /Icons/items/<file>.png paths instead of clobbering
// them with the (currently 403'ing) BunnyCDN URLs.
const LOCAL_ICONS = new Set<string>(iconManifest as string[]);
function localizeIconUrl(url: string | undefined): string | undefined {
  if (!url) return url;
  if (url.startsWith('/Icons/items/')) return url;
  const fn = decodeURIComponent(url.split('/').pop()?.split('?')[0] || '');
  if (!fn || fn === '40x40' || fn.includes('placehold')) return url;
  if (LOCAL_ICONS.has(fn)) return `/Icons/items/${fn}`;
  const base = fn.replace(/_\d+(\.png)$/i, '$1');
  if (base !== fn && LOCAL_ICONS.has(base)) return `/Icons/items/${base}`;
  return url;
}

// Localization map (key → English display name). Generated by
// scripts/localize-item-names.js from the in-game localization tables.
const NAME_MAP = nameManifest as Record<string, string>;
function localizeName(name: string | undefined): string | undefined {
  if (typeof name !== 'string') return name;
  if (!/Key$/.test(name) || /\s/.test(name)) return name;
  return NAME_MAP[name] || name;
}

const API_BASE = process.env.BEASTBURST_API_URL || 'https://developers.beastburst.com/api/community';
const API_TOKEN = process.env.BEASTBURST_API_TOKEN || '';
const CRON_SECRET = process.env.CRON_SECRET || '';

async function fetchPage(page: number) {
  const res = await fetch(`${API_BASE}/items?page=${page}`, {
    headers: {
      'Authorization': `Bearer ${API_TOKEN}`,
      'X-API-Version': '2.0.0',
      'Accept': 'application/json',
    },
  });
  if (!res.ok) throw new Error(`API error page ${page}: ${res.status}`);
  return res.json();
}

interface BeastBurstItem {
  id: string;
  name: string;
  type: string;
  rarity: string;
  icon: string;
  slot_type: string;
  stack_size: number;
  is_destructible: boolean;
  sell_value: number;
  stat_configuration?: {
    lists?: Array<{
      modifications?: Array<{
        stat: string;
        modif_type: string;
        modif_weight: number;
        modif_min_value: string;
        modif_max_value: string;
      }>;
    }>;
  };
}

function mapItem(item: BeastBurstItem, slug: string | undefined) {
  const doc: { _id: string; _type: string; [key: string]: unknown } = {
    _type: 'item',
    _id: 'item-' + item.id,
    name: localizeName(item.name) || item.name,
    itemType: item.type,
    rarity: item.rarity,
    icon: localizeIconUrl(item.icon),
    slotType: item.slot_type,
    stackSize: item.stack_size,
    isDestructible: item.is_destructible,
    sellValue: item.sell_value,
    externalId: item.id,
    ...(slug ? { slug: { _type: 'slug', current: slug } } : {}),
  };

  const mods = item.stat_configuration?.lists?.[0]?.modifications;
  if (mods?.length) {
    doc.stats = mods.map((mod) => ({
      _type: 'itemStat',
      _key: mod.stat || String(Math.random()).slice(2, 10),
      stat: mod.stat,
      modifType: mod.modif_type,
      modifWeight: mod.modif_weight,
      minValue: mod.modif_min_value,
      maxValue: mod.modif_max_value,
    }));
  }

  return doc;
}

export async function GET(request: NextRequest) {
  // Auth check - Vercel cron sends this header, manual calls use query param
  const authHeader = request.headers.get('authorization');
  const querySecret = request.nextUrl.searchParams.get('secret');
  const validAuth = authHeader === `Bearer ${CRON_SECRET}` || querySecret === CRON_SECRET;

  if (!validAuth) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    // Fetch all items from BeastBurst
    const firstPage = await fetchPage(1);
    const lastPage = firstPage.meta.last_page;
    let allItems: BeastBurstItem[] = [...firstPage.data.items];

    for (let page = 2; page <= lastPage; page++) {
      const data = await fetchPage(page);
      allItems = allItems.concat(data.data.items);
    }

    // Resolve slugs (preserve existing, assign new)
    const existingRows = await sanityWriteClient.fetch<Array<{ externalId: string; slug: string }>>(
      `*[_type == "item" && defined(slug.current)]{ externalId, "slug": slug.current }`,
    );
    const existing = new Map<string, string>();
    for (const r of existingRows) existing.set(r.externalId, r.slug);
    // Slug from the localized name so URLs are based on the player-facing string.
    const slugMap = assignSlugs(
      allItems.map((i) => ({ id: i.id, name: localizeName(i.name) || i.name })),
      existing,
    );

    // Write to Sanity in batches
    const docs = allItems.map((i) => mapItem(i, slugMap.get(i.id)));
    const BATCH_SIZE = 20;
    let written = 0;

    for (let i = 0; i < docs.length; i += BATCH_SIZE) {
      const batch = docs.slice(i, i + BATCH_SIZE);
      let tx = sanityWriteClient.transaction();
      for (const doc of batch) {
        tx = tx.createOrReplace(doc);
      }
      await tx.commit();
      written += batch.length;
    }

    return NextResponse.json({
      success: true,
      message: `Imported ${written} items from ${lastPage} pages`,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    return NextResponse.json(
      { error: 'Import failed', details: String(error) },
      { status: 500 }
    );
  }
}
